=head0 *Prefazione

=encoding utf8

I<Modern Perl> è uno dei modi per descrivere il modo in cui lavorano i migliori programmatori Perl 5. 
Usano idiomi del linguaggio. Si avvantaggiano di CPAN. 
Mostrano senso estetico e arte nello scrivere codice potente, manutenibile, scalabile, conciso ed efficace. 
Anche voi potete imparare a lavorare così!

Perl ha fatto la sua comparsa nel 1987 come semplice strumento per gli amministratori di sistema.
Sebbene agli inizi si proponesse di occupare una nicchia tra lo scripting shell e la programmmazione C,
col tempo è diventato un potente linguaggio general-purpose.
Perl 5 ha una solida storia di pragmatismo e un brillante futuro di raffinamenti e migliorie
N<Perl 6 è una reinvenzione della programmazione basata sui solidi principi base del Perl, ma è un argomento per un altro libro.>.

Durante la ormai lunga storia di Perl--specialmente i 17 anni di Perl 5--la nostra percezione di che cosa sia un programma Perl eccellente è cambiata. 
Se da una parte potete scrivere programmi efficaci senza avvantaggiarvi di tutto ciò che il linguaggio vi offre,
dall'altra la comunità Perl globale ha inventato, preso a prestito, migliorato, e raffinato molte idee e le ha rese disponibili a chiunque le voglia apprendere.

=head1 Usare Modern Perl

Il modulo Modern::Perl, disponibile su CPAN (L<cpan>), richiede a Perl di segnalare l'uso di costrutti dubbi e errori di battitura, 
e attiva nuove funzionalità introdotte nelle versioni recenti di Perl 5. Assumete che ogni esempio in questo libro inizi con:

=begin programlisting

    use Modern::Perl;

=end programlisting

Se per qualche ragione non potete installare questo modulo, potete iniziare i vostri programmi con il seguente codice che è approssimativamente equivalente:

=begin programlisting

    use 5.012;
    use strict;
    use warnings;
    use autodie;

=end programlisting

A meno di diversa indicazione, i pezzi di codice presentati assumono sempre il seguente scheletro base di programma:

=begin programlisting

    #!/usr/bin/perl

    use Modern::Perl;

    # di seguito il codice dell'esempio

=end programlisting

Altri pezzi di codice utilizzano funzioni di test come C<ok()>, C<like()> e
C<is()> (L<testing>). In questo caso il programma scheletro è:

=begin programlisting

    #!/usr/bin/perl

    use Modern::Perl;
    B<use Test::More;>

    # di seguito il codice dell'esempio

    done_testing();

=end programlisting

Al momento della scrittura di questo libro, la famiglia di versioni stabili di Perl 5 è Perl 5.14.
Gli esempi in questo libro funzionano al meglio con Perl 5.12.0 o successivi. 
Molti esempi funzionano, con piccole modifiche, anche con versioni di Perl 5 più datate, ma incontrerete difficoltà
maggiori con le versioni più vecchie di 5.10.0. 

X<Strawberry Perl>
X<ActivePerl>
X<perlbrew>
X<CPAN; C<App::perlbrew>>

Se non avete un'installazione di Perl 5 (o ne avete una vecchia versione), potete installare voi stessi una nuova release.
Gli utenti Windows possono scaricare Strawberry Perl da U<http://www.strawberryperl.com/> oppure ActivePerl da U<http://www.activestate.com/activeperl>.
Gli utenti di altri sistemi operativi che hanno già Perl 5 installato (insieme a un compilatore C e gli altri tool di sviluppo),
possono iniziare con l'installare il modulo CPAN C<App::perlbrew>N<Si veda U<http://search.cpan.org/perldoc?App::perlbrew> per le istruzioni di installazione.>.

C<perlbrew> vi consente di installare e gestire più versioni di Perl 5. 
In questo modo, potete passare da una versione di Perl 5 all'altra e, inoltre, 
potete installare Perl 5 e i moduli CPAN nella vostra home directory senza interferire con la versione del Perl di sistema.
Se avete mai dovuto pregare il vostro amministratore di sistema per avere il permesso di installare del software,
vi dovrebbe essere chiaro come questo vi possa semplificare, e di molto, la vita.

=head1 Riconoscimenti

Questo libro non sarebbe stato possibile senza
le domande, i commenti, i suggerimenti, i consigli, la saggezza e
l'incoraggiamento di tanta, tanta gente. In particolare, l'autore e
l'editore vogliono ringraziare:

John SJ Anderson, Peter Aronoff, Lee Aylward, Alex Balhatchet, Ævar Arnfjörð
Bjarmason, Matthias Bloch, John Bokma, Vasily Chekalkin, Dmitry Chestnykh, E.
Choroba, Anneli Cuss, Paulo Custodio, Steve Dickinson, Kurt Edmiston, Felipe,
Shlomi Fish, Jeremiah Foster, Mark Fowler, John Gabriele, Andrew Grangaard,
Bruce Gray, Ask Bjørn Hansen, Tim Heaney, Graeme Hewson, Robert Hicks, Michael
Hind, Mark Hindess, Yary Hluchan, Mike Huffman, Gary H. Jones II, Curtis
Jewell, Mohammed Arafat Kamaal, James E Keenan, Kirk Kimmel, Yuval Kogman, Jan
Krynicky, Michael Lang, Jeff Lavallee, Moritz Lenz, Andy Lester, Jean-Baptiste
Mazon, Josh McAdams, Gareth McCaughan, John McNamara, Shawn M Moore, Alex
Muntada, Carl Mäsak, Chris Niswander, Nelo Onyiah, Chas. Owens, ww from
PerlMonks, Jess Robinson, Dave Rolsky, Gabrielle Roth, Eduardo Santiago, Andrew
Savige, Lorne Schachter, Steve Schulze, Dan Scott, Alexander Scott-Johns,
Phillip Smith, Christopher E. Stith, Mark A. Stratman, Bryan Summersett, Audrey
Tang, Scott Thomson, Ben Tilly, Ruud H. G. van Tol, Sam Vilain, Larry Wall,
Lewis Wall, Colin Wetherbee, Frank Wiegand, Doug Wilson, Sawyer X, David
Yingling, Marko Zagozen, harleypig, hbm e sunnavy.

Gli errori rimanenti sono colpa esclusiva della testardaggine dell'autore.

=head1 Traduzione

Questa traduzione è stata effettuata dall'Associazione di Promozione Sociale
B<Perl.it>, nelle persone di: TODO.
